### ISSUE TITLE
bartCause parameter and interpretation of results

### ISSUE THREAD

**Issue by k-b-1** [priism-center/thinkCausal_dev#38]
First of all, thanks for this great tool!
It would help, if I could see the bartCause call including the parameter depending on my choices in the UI.
Furthermore, I need help more help to interpret the results. For example, I have an ATE of 0.79 but the interpretation box holds the text "For participants in this study, receiving the treatment led to an increase of 0.59 units compared to what would have happened if participants did not receive the treatment." It seems that 0.59 is the mean. The mean of what? And why is it not the ATE that explains for this difference? 

Many thanks in advance.
Klaus

**Comment by joemarlo** [comment]
Hi Klaus - Apologies for the delayed response. I'm tagging @gperrett so he can address

**Comment by gperrett** [comment]
Hi Klaus thank you for your feedback! I have made changes to the UI to make it clear which variables are included in the model. The interpretation section has also been updated. As for the ATE, I'm not sure I understand your comment. Would you like to connect over zoom and we can discuss?
